### PR TITLE
Automate tests

### PR DESCRIPTION
**Pull request by celesterobinson**
This PR adds a new workflow to run automated tests using sauce labs on new PRs and pushes.

### CODE REVIEW

**Comment by Aaronius** [comment]
Hey @celesterobinson, do you know what remains here? Chrome problems?

**Comment by celesterobinson** [comment]
I can't remember the exact issue, but yeah there were issues with Chrome actually launching the test suite. I think I kind of came to the conclusion that SauceLabs might not be the right solution with Github Actions though.

**Comment by celesterobinson** [comment]
I think the biggest hurdle I was facing was using saucectl. It requires [Cypress, Playwright, or TestCafe.](https://docs.saucelabs.com/dev/cli/saucectl/). I was trying to make it work without one of those frameworks, but hadn't had any luck yet. So we could incorporate one or use something other than SauceLabs like Browserstack. I think we'd still need TestCafe or something similar for that though.

**Comment by Aaronius** [comment]
Hey @celesterobinson, I think we should switch to BrowserStack. I'm going to close this PR. Thanks for your efforts!

**Comment by celesterobinson** [comment]
Sounds good! Sorry I haven't had a chance to get back at this yet. I think browser stack is a good move

**Pull request closed without merging**
