### PR TITLE
Type fixes & acceptance tests

### PR DESCRIPTION
**Pull request by mike-north**
- Fixes type compile errors introduced by #22 
- Type-safety around "promisified" methods object, invoked through postMessage channel (see included tests that demonstrate this)
- Type information is now tested via `dtslint`, w/ acceptance tests based around README examples

### CODE REVIEW

**Comment by ahtcx** [comment]
What compile errors were you getting?

**Comment by Aaronius** [comment]
Thanks @mike-north, especially for hooking up tests. @paulblyth If you ever have a moment I'd like to get your review on this as well.

**Comment by mike-north** [comment]
> What compile errors were you getting?

you had 

https://github.com/Aaronius/penpal/blob/8c7d9f0e98f785caf83f3a84bf4fe061a4cde663/src/index.d.ts#L12-L14

and are using it in several places without providing a generic argument

https://github.com/Aaronius/penpal/blob/8c7d9f0e98f785caf83f3a84bf4fe061a4cde663/src/index.d.ts#L3
https://github.com/Aaronius/penpal/blob/8c7d9f0e98f785caf83f3a84bf4fe061a4cde663/src/index.d.ts#L8
(and more)

Additionally, the types around parent/child connection methods weren't offering any type safety, or properly taking into account that

```ts
{
   add(number, number): number
}
```
turns into 
```ts
{
   add(number, number): Promise<number>
}
```

**Comment by mike-north** [comment]
Remaining test failures are likely due to forks not having access to your sauce labs credentials (in travis, forks have no environment variables for security reasons)

**Comment by Aaronius** [comment]
In the file that gets emitted as lib/index.d.ts, my IDE (Webstorm) is flagging this line:

`Promise: typeof Promise;`

It says: `TS2693: 'Promise' only refers to a type, but is being used as a value here.` Is this a cause for concern?

**Comment by Aaronius** [comment]
Oddly, I don't get that flag in types/index.d.ts. I might need to research this one.

**Comment by Aaronius** [comment]
Ah, it's because tsconfig.json isn't in `lib`. This doesn't concern me.

**Comment by mike-north** [comment]
> Ah, it's because tsconfig.json isn't in lib. This doesn't concern me.

typically I like to keep the `tsconfig.json` in a subfolder unless type-checking or TS compilation is necessary for _building the library_. Even in that case, it's usually desirable to have a different config for declarations.

**Comment by Aaronius** [comment]
Published in 3.0.5.

**Comment by Aaronius** [comment]
Thanks again for putting the work into this.

**Pull request merged**
